### PR TITLE
Dynamic font size support for events and repo list

### PR DESCRIPTION
**Pull request by mlvea**
Fixed dynamic font sizing for events list and repo list which make it more accessible for people with vision disabilities. 

Set Team to None so that anyone can run without errors after pod install.

### CODE REVIEW

**Comment by sayanee** [comment]
Tested locally 🎉 

screenshot 2016-05-30 19 26 47

screenshot 2016-05-30 19 26 56

screenshot 2016-05-30 19 27 05

**Comment by sayanee** [comment]
@madnik thank you so much for this very important feature! We want people who with vision challenges to also attend these open meetups ❤️  

I have released on App Store as part of [v1.2.1](https://github.com/webuildsg/iOS/releases/tag/v1.2.1). I'm guessing I don't have to do anything else. I'm releasing an update for an iOS app for the first time.

image

**Comment by sayanee** [comment]
Oops! Just figured how to submit again `v1.2.1`:

image

**Comment by mlvea** [comment]
Great! And most welcome. Looking forward for the version.

**Pull request merged**
